# Generated by Django 4.0.2 on 2022-04-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('patient_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('similarity', models.FloatField()),
                ('roi_dose', models.FloatField()),
                ('ptv_dose', models.FloatField()),
                ('ptv_volume', models.FloatField()),
                ('roi_roi_distance', models.FloatField()),
                ('roi_roi_overlap', models.FloatField()),
                ('rt_dose', models.FloatField()),
                ('roi', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('institutiona', models.CharField(max_length=200)),
            ],
        ),
    ]
