# Generated by Django 4.0.2 on 2022-04-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_treatment_institutiona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedFile', models.FileField(upload_to='Uploaded_DICOM/')),
            ],
        ),
        migrations.AlterField(
            model_name='treatment',
            name='similarity',
            field=models.FloatField(null=True),
        ),
    ]
