# Generated by Django 4.0.2 on 2022-04-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_document_alter_treatment_similarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='parsed_dicom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, null=True)),
                ('patient_birthday', models.CharField(max_length=200, null=True)),
                ('patient_sex', models.CharField(max_length=100, null=True)),
                ('patient_ethnic_group', models.CharField(max_length=100, null=True)),
                ('study_instance_uid', models.CharField(max_length=200, null=True)),
                ('study_date', models.CharField(max_length=200, null=True)),
                ('study_description', models.CharField(max_length=1000, null=True)),
                ('series_instance_uid', models.CharField(max_length=200, null=True)),
                ('series_date', models.CharField(max_length=200, null=True)),
                ('series_description', models.CharField(max_length=1000, null=True)),
                ('modality', models.CharField(max_length=200, null=True)),
                ('series_number', models.CharField(max_length=200, null=True)),
                ('physicians_of_record', models.CharField(max_length=200, null=True)),
                ('manufacturer', models.CharField(max_length=200, null=True)),
                ('sop_instance_uid', models.CharField(max_length=200, null=True)),
                ('sop_class_uid', models.CharField(max_length=200, null=True)),
                ('image_type', models.CharField(max_length=200, null=True)),
                ('photo_metric_interpretation', models.CharField(max_length=1000, null=True)),
                ('rescale_slope', models.CharField(max_length=200, null=True)),
                ('rescale_intercept', models.CharField(max_length=200, null=True)),
                ('slice_location', models.CharField(max_length=200, null=True)),
                ('pixel_spacing', models.CharField(max_length=200, null=True)),
                ('image_orientation_patient', models.CharField(max_length=200, null=True)),
                ('image_position_patient', models.CharField(max_length=200, null=True)),
                ('slice_thickness', models.CharField(max_length=200, null=True)),
                ('body_part_examined', models.CharField(max_length=200, null=True)),
                ('roi_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
