# Generated by Django 4.0.2 on 2022-04-09 01:13

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_parsed_dicom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='similarity',
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(upload_to='Uploaded_DICOM/'),
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(null=True)),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.treatment')),
            ],
        ),
    ]
