# Generated by Django 4.0.2 on 2022-04-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_treatment_similarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed_dicom',
            name='upload_time',
            field=models.DateTimeField(null=True),
        ),
    ]
