# Generated by Django 4.0.2 on 2022-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_parsed_dicom_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsed_dicom',
            name='upload_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
