# Generated by Django 4.0.2 on 2022-04-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_parsed_dicom_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsed_dicom',
            name='upload_time',
            field=models.DateTimeField(null=True),
        ),
    ]
